#!/bin/bash

export JAVA_HOME=/usr/local/jdk1.8.0_251/
export TOMCAT_HOME=/usr/local/apache-tomcat-8.5.55

case $1 in
start)
  sh $TOMCAT_HOME/bin/startup.sh
;;
stop)
  sh $TOMCAT_HOME/bin/shutdown.sh
;;
restart)
  sh $TOMCAT_HOME/bin/shutdown.sh
  sh $TOMCAT_HOME/bin/startup.sh
;;
esac
exit 0