server:
  port: 8080
  servlet:
    context-path: /

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false