server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.202/matigou_cloud
      username: 'root'
      password: '000000'
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 1
      validation-query-timeout: 500
      filters: stat
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id
      refresh-mapper: true
    banner: false
  datacenter-id: 1
  worker-id: 1
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.matigou.ucenter.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false